routes/web.php
<?php

use App\Http\Controllers\Admin\AdresseController;
use App\Http\Controllers\Admin\CaracteristiqueController;
use App\Http\Controllers\Admin\CategorieProduitController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ClimatController;
use App\Http\Controllers\Admin\CommandeController;
use App\Http\Controllers\Admin\DinoController;
use App\Http\Controllers\Admin\DinoEnclosController;
use App\Http\Controllers\Admin\EnclosController;
use App\Http\Controllers\Admin\EnvironnementController;
use App\Http\Controllers\Admin\EspeceController;
use App\Http\Controllers\Admin\ModeLivraisonController;
use App\Http\Controllers\Admin\NourritureController;
use App\Http\Controllers\Admin\PaysController;
use App\Http\Controllers\Admin\PersonnelController;
use App\Http\Controllers\Admin\ProduitController;
use App\Http\Controllers\Admin\StatutCommandeController;
use App\Http\Controllers\Admin\TaxeController;
use App\Http\Controllers\Admin\TypeEnclosController;
use App\Http\Controllers\Admin\TypePersonnelController;
use App\Http\Controllers\FrontProduitController;
use App\Http\Controllers\PasserCommandeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

//Route::get('/', function () {
//    return view('welcome');
//});
//
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');


Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//admin
Route::get('/admin', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
Route::resource('/admin/caracteristiques', CaracteristiqueController::class);
Route::resource('/admin/categories-de-produit', CategorieProduitController::class);
Route::resource('/admin/climats', ClimatController::class);
Route::resource('/admin/enclos', EnclosController::class);
Route::resource('/admin/environnements', EnvironnementController::class);
Route::resource('/admin/especes', EspeceController::class);
Route::resource('/admin/modes-de-livraison', ModeLivraisonController::class);
Route::resource('/admin/nourritures', NourritureController::class);
Route::resource('/admin/pays', PaysController::class);
Route::resource('/admin/statuts-commandes', StatutCommandeController::class);
Route::resource('/admin/taxes', TaxeController::class);
Route::resource('/admin/types-enclos', TypeEnclosController::class);
Route::resource('/admin/types-personnel', TypePersonnelController::class);

Route::resource('/admin/adresses', AdresseController::class);
Route::resource('/admin/clients', ClientController::class);
Route::resource('/admin/commandes', CommandeController::class);
Route::resource('/admin/dinos', DinoController::class);
Route::resource('/admin/dino-enclos', DinoEnclosController::class)->only([
    'index', 'destroy'
]);
Route::resource('/admin/produits', ProduitController::class);
Route::resource('/admin/personnel', PersonnelController::class);

//test
Route::resource('/commander', PasserCommandeController::class);
Route::GET("/commander/panier/{id}", [PasserCommandeController::class, 'panierAdd'])->name('panier.add');
Route::GET("/commander/{id}", [PasserCommandeController::class, 'show'])->name('commander.show');
Route::POST("/commander/commande", [PasserCommandeController::class, 'commander'])->name('commander.commander');
Route::POST("/commander/validation", [PasserCommandeController::class, 'validation'])->name('commander.validation');
Route::get("/commander/panier", [PasserCommandeController::class, 'panier'])->name('panier');

require __DIR__.'/auth.php';

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Client extends Model
{
    use HasFactory;

    protected $fillable = ['prenom', 'nom', 'tel', 'adresse_livraison_id', 'adresse_facturation_id', 'user_id'];

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo
     */
    public function adresseLivraison()
    {
        return $this->belongsTo(Adresse::class);
    }

    /**
     * @return BelongsTo
     */
    public function adresseFacturation()
    {
        return $this->belongsTo(Adresse::class);
    }

    /**
     * @return HasMany
     */
    public function commandes()
    {
        return $this->hasMany(Commande::class);
    }

    /**
     * @return BelongsToMany
     */
    public function produits()
    {
        return $this->belongsToMany(Produit::class, 'panier')
            ->withPivot('quantite')
            ->withTimestamps();
    }

    /**
     * @return BelongsToMany
     */
    public function adresses()
    {
        return $this->belongsToMany(Adresse::class, 'gestion')
            ->withTimestamps();
    }

    /**
     * @return string
     */
    public function getFullName()
    {
        return $this->prenom . ' ' . $this->nom;
    }

    /**
     * @return string
     */
    public function getAdresseLivraison(): string
    {

        $adresse = $this->adresseLivraison->numero
            . ', '
            . $this->adresseLivraison->rue
            . ' '
            . $this->adresseLivraison->cp
            . ' '
            . $this->adresseLivraison->ville
            . ' / '
            . $this->adresseLivraison->pays->nom;

        return $adresse;
    }

    /**
     * @return string
     */
    public function getAdresseFacturation(): string
    {
        $adresse = $this->adresseFacturation->numero
            . ', '
            . $this->adresseFacturation->rue
            . ', '
            . $this->adresseFacturation->cp
            . ' '
            . $this->adresseFacturation->ville
            . ' / '
            . $this->adresseFacturation->pays->nom;

        return $adresse;
    }

}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\SaveAdresseLivraisonRequest;
use App\Http\Requests\SaveClientRequest;
use App\Models\Adresse;
use App\Models\Client;
use App\Models\Pays;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


class ClientController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $clients = Client::with('adresseLivraison:id,numero,rue,cp,ville,pays_id', 'adresseFacturation:id,numero,rue,cp,ville,pays_id')
            ->select('id', 'prenom', 'nom', 'tel', 'adresse_livraison_id', 'adresse_facturation_id')
            ->orderByDesc('created_at')
            ->get();

        return view('admin.client.index', ['clients' => $clients]);
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        $client = new Client();
        $adresseLivraison = new Adresse();
        $adresse = new Adresse();
        $pays = Pays::pluck('nom', 'id');

        return view('admin.client.create', [
            'client' => $client,
            'adresseLivraison' => $adresseLivraison,
            'adresse' => $adresse,
            'pays' => $pays,
        ]);
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request                     $request,
                          SaveAdresseLivraisonRequest $requestLivraison,
                          SaveClientRequest           $requestClient)
    {
        $addresseLivraison = Adresse::create([
            'numero' => $requestLivraison->numeroLivraison,
            'rue' => $requestLivraison->rueLivraison,
            'cp' => $requestLivraison->cpLivraison,
            'ville' => $requestLivraison->villeLivraison,
            'pays_id' => $requestLivraison->paysLivraison,
        ]);

        if ($request->numero !== null && $request->rue !== null && $request->cp !== null && $request->ville !== null && $request->pays_id !== null) {
            $addresseFacturation = Adresse::create($request->all());
        } else {
            $addresseFacturation = $addresseLivraison;
        }

        $client = Client::create([
            'prenom' => $requestClient->prenom,
            'nom' => $requestClient->nom,
            'tel' => $requestClient->tel,
            'adresse_livraison_id' => $addresseLivraison->id,
            'adresse_facturation_id' => $addresseFacturation->id,
        ]);

        return redirect()->route('clients.index')
            ->with('success', 'Vous venez d\'ajouter un nouveau client');
    }

    /**
     * @param $id
     * @return Application|Factory|View
     */
    public function show($id)
    {
        $client = Client::find($id);
        return view('admin.client.show', ['client' => $client]);
    }

    /**
     * @param $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $client = Client::find($id);
        $adresseLivraison = Adresse::find($client->adresse_livraison_id);
        $adresse = Adresse::find($client->adresse_facturation_id);
        $pays = Pays::pluck('nom', 'id');

        return view('admin.client.edit', [
            'client' => $client,
            'adresseLivraison' => $adresseLivraison,
            'adresse' => $adresse,
            'pays' => $pays,
        ]);
    }

    /**
     * @param Request $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(Request                     $request,
                           SaveAdresseLivraisonRequest $requestLivraison,
                           SaveClientRequest           $requestClient,
                           int                         $id)
    {
        $client = Client::find($id);

        $addresseLivraison = Adresse::find($client->adresse_livraison_id);
        $addresseFacturation = Adresse::find($client->adresse_facturation_id);

        $addresseLivraison->update([
            'numero' => $requestLivraison->numeroLivraison,
            'rue' => $requestLivraison->rueLivraison,
            'cp' => $requestLivraison->cpLivraison,
            'ville' => $requestLivraison->villeLivraison,
            'pays_id' => $requestLivraison->paysLivraison,
        ]);

        if ($request->numero !== null && $request->rue !== null && $request->cp !== null && $request->ville !== null && $request->pays_id !== null) {
            $addresseFacturation->update($request->all());
        } else {
            $addresseFacturation = $addresseLivraison;
        }

        $client->update([
            'prenom' => $requestClient->prenom,
            'nom' => $requestClient->nom,
            'tel' => $requestClient->tel,
            'adresse_livraison_id' => $addresseLivraison->id,
            'adresse_facturation_id' => $addresseFacturation->id,
        ]);

        return redirect()->route('clients.index')
            ->with('success', 'Le client à bien été modifié');
    }

    /**
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        Client::find($id)->delete();

        return redirect()->route('clients.index')
            ->with('success', 'Le client à bien été supprimé');
    }
}

resources/views/admin/client/create.blade.php
@extends('admin.base')

@section('title', 'Créer un client')

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('clients.create')}}">Créer un client</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @includeif('partials.errors')
            <div class="card border-dark">
                <div class="card-header bg-dark">
                    <h5 class="card-title m-0">Ajouter</h5>
                </div>
                <div class="card-body">
                    {!! Form::open(['method' => 'POST', 'route' => 'clients.store']) !!}
                    @csrf
                    @include('admin.client.form')

                    <div class="col-12 my-2">
                        <h2 class="h3 font-weight-bold">Adresse de facturation</h2>
                        <fieldset>Si votre adresse de facturation est différente de votre adresse de livraison, veuillez clicker sur le bouton ci-dessous:<br>
                        <a class="btn btn-secondary my-3" href="#" data-toggle="collapse" data-target="#target1">
                            Adresse facturation
                        </a>
                        <div id="target1" class="collapse">
                            @include('admin.adresse.form')
                        </div>
                        </fieldset>
                    </div>

                        {{ Form::submit('Ajouter',['class'=>'btn btn-success mt-3']) }}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/client/edit.blade.php
@extends('admin.base')

@section('title', 'Modifier le client')

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('clients.edit', $client->id)}}">Modifier le client</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @includeif('partials.errors')
            <div class="card border-dark">
                <div class="card-header bg-dark">
                    <h5 class="card-title m-0">Modifier</h5>
                </div>
                <div class="card-body">
                    {!! Form::open(['method' => 'PUT', 'route' => ['clients.update', $client->id]]) !!}
                    {{ method_field('PATCH') }}
                    @csrf
                    @include('admin.client.form')

                    <div class="col-12 my-2">
                        <h2 class="h3 font-weight-bold">Adresse de facturation</h2>
                        <fieldset>Si votre adresse de facturation est différente de votre adresse de livraison, veuillez clicker sur le bouton ci-dessous:<br>
                            <a class="btn btn-secondary my-3" href="#" data-toggle="collapse" data-target="#target1">
                                Adresse facturation
                            </a>
                            <div id="target1" class="collapse">
                                @include('admin.adresse.form')
                            </div>
                        </fieldset>
                    </div>

                    {{ Form::submit('Modifier',['class'=>'btn btn-primary mt-3']) }}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/client/form.blade.php
<div class="row">
    <h2 class="h3 font-weight-bold">Informations personnels</h2>
    <div class="col-12 col-lg-4">
        <div class="form-group mt-3">
            {{ Form::label('Prénom :') }}
            {{ Form::text('prenom', $client->prenom, ['class' => 'form-control mb-3' . ($errors->has('prenom') ? ' is-invalid' : ''), 'placeholder' => 'Prénom']) }}
            @error('prenom')
            <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
            @enderror
        </div>
    </div>
    <div class="col-12 col-lg-4">
        <div class="form-group mt-3">
            {{ Form::label('Nom :') }}
            {{ Form::text('nom', $client->nom, ['class' => 'form-control mb-3' . ($errors->has('nom') ? ' is-invalid' : ''), 'placeholder' => 'Nom']) }}
            @error('nom')
            <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
    </span>
            @enderror
        </div>
    </div>
    <div class="col-12 col-lg-4">
        <div class="form-group mt-3">
            {{ Form::label('Numéro de téléphone :') }}
            {{ Form::text('tel', $client->tel, ['class' => 'form-control mb-3' . ($errors->has('tel') ? ' is-invalid' : ''), 'placeholder' => 'Numéro de téléphone']) }}
            @error('tel')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
    </div>
    <h2 class="h3 font-weight-bold">Adresse de livraison</h2>
    <div class="col-12 col-lg-3">
        <div class="form-group mt-3">
            {{ Form::label('Numéro :') }}
            {{ Form::text('numeroLivraison', $adresseLivraison->numero, ['class' => 'form-control' . ($errors->has('numeroLivraison') ? ' is-invalid' : ''), 'placeholder' => 'Numéro']) }}
            @error('numeroLivraison')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
    </div>
    <div class="col-12 col-lg-9">
        <div class="form-group mt-3">
            {{ Form::label('Rue :') }}
            {{ Form::text('rueLivraison', $adresseLivraison->rue, ['class' => 'form-control' . ($errors->has('rueLivraison') ? ' is-invalid' : ''), 'placeholder' => 'Rue']) }}
            @error('rueLivraison')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
    </div>
    <div class="col-12 col-lg-4">
        <div class="form-group mt-3">
            {{ Form::label('Code postal :') }}
            {{ Form::text('cpLivraison', $adresseLivraison->cp, ['class' => 'form-control' . ($errors->has('cpLivraison') ? ' is-invalid' : ''), 'placeholder' => 'Code postal']) }}
            @error('cpLivraison')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
    </div>
    <div class="col-12 col-lg-4">
        <div class="form-group mt-3">
            {{ Form::label('Ville :') }}
            {{ Form::text('villeLivraison', $adresseLivraison->ville, ['class' => 'form-control' . ($errors->has('villeLivraison') ? ' is-invalid' : ''), 'placeholder' => 'Ville']) }}
            @error('villeLivraison')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
    </div>
    <div class="col-12 col-lg-4">
        <div class="form-group mt-3">
            {{ Form::label('Pays :') }}
            @if(isset($adresseLivraison->pays->nom))
                {{ Form::select('paysLivraison', $pays, $adresseLivraison->pays_id,['class' => 'form-select'. ($errors->has('villeLivraison') ? ' is-invalid' : '')]) }}
            @else
                {{ Form::select('paysLivraison', $pays, null,['class' => 'form-select'. ($errors->has('villeLivraison') ? ' is-invalid' : ''), 'placeholder' => '-- Choisir un pays --']) }}
            @endif
            @error('paysLivraison')
            <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
            @enderror
        </div>
    </div>
</div>

resources/views/admin/client/index.blade.php
@extends('admin.base')

@section('title', 'Clients')

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('clients.index')}}">Clients</a>
@endsection

@section('add')
    <a class="btn btn-primary" href="{{ route('clients.create') }}">Ajouter</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif

            <div class="container-fluid border border-dark rounded pt-3 pb-2">
                <table class="admin_index table table-striped table-light table-hover nowrap" width="100%">

                    <thead class="table-dark">
                    <tr>
                        <th  data-priority="1">id</th>
                        <th  data-priority="2">Client</th>
                        <th>Adresse de livraison</th>
                        <th>Adresse de facturation</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>@foreach ($clients as $client)
                        <tr>
                            <td>{{ $client->id }}</td>
                            <td>
                               <b>
                                   {{ $client->getFullname() }}
                               </b>
                                <br>
                                {{ $client->tel }}
                            </td>
                            <td>
                                @if($client->adresseLivraison != null)
                                {{ $client->getAdresseLivraison() }}
                                @else
                                    Ce client n'as pas enregistré d'adresse de livraison
                                @endif
                            </td>
                            <td>
                                @if($client->adresseFacturation != null)
                                {{ $client->getAdresseFacturation() }}
                                @else
                                    Ce client n'as pas enregistré d'adresse de facturation
                                @endif
                            </td>
                            <td>
                                <form action="{{ route('clients.destroy',$client->id) }}" method="POST">
                                    <a class="btn btn-sm btn-primary "
                                       href="{{ route('clients.show',$client->id) }}"><i
                                            class="fa fa-fw fa-eye"></i> Montrer</a>
                                    <a class="btn btn-sm btn-success"
                                       href="{{ route('clients.edit',$client->id) }}"><i
                                            class="fa fa-fw fa-edit"></i> Modifer</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm"><i
                                            class="fa fa-fw fa-trash"></i> Supprimer
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/client/show.blade.php
@extends('admin.base')

@section('title', 'Client "' . $client->nom .'"' )

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('clients.create')}}">Client
        <span>{{ $client->nom }}</span></a>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card border-dark">
                <div class="card-header d-flex align-items-center bg-dark">
                    <h5 class="card-title m-0">Ajouter</h5>
                    <div class="d-flex justify-content-end w-100">
                        <a class="btn btn-primary" href="{{ route('clients.index') }}">Retour</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 col-lg-4">
                                <div class="form-group">
                                    <b>Identifiant :</b>
                                    {{ $client->id }}
                                </div>
                                <div class="form-group">
                                    <b>Client :</b>
                                    {{ $client->getfullname() }}
                                </div>
                                <div class="form-group">
                                    <b>Téléphone :</b>
                                    {{ $client->tel }}
                                </div>
                            </div>
                            <div class="col-12 col-lg-4">
                                <div class="form-group">
                                    <b>Adresse livraison :</b><br>
                                    @if($client->adresseLivraison != null)
                                        {{ $client->getAdresseLivraison() }}
                                    @else
                                        Ce client n'as pas enregistré d'adresse de livraison
                                    @endif
                                </div>
                                <div class="form-group">
                                    <b>Adresse facturation :</b><br>
                                    @if($client->adresseFacturation != null)
                                        {{ $client->getAdresseFacturation() }}
                                    @else
                                        Ce client n'as pas enregistré d'adresse de facturation
                                    @endif
                                </div>
                            </div>
                            <div class="col-12 col-lg-4">
                                <div class="form-group">
                                    <b>Date d'ajout :</b>
                                    {{ $client->created_at }}
                                </div>
                                <div class="form-group">
                                    <b>Date de modification :</b>
                                    {{ $client->updated_at }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection