routes/web.php
<?php

use App\Http\Controllers\Admin\AdresseController;
use App\Http\Controllers\Admin\CaracteristiqueController;
use App\Http\Controllers\Admin\CategorieProduitController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ClimatController;
use App\Http\Controllers\Admin\CommandeController;
use App\Http\Controllers\Admin\DinoController;
use App\Http\Controllers\Admin\DinoEnclosController;
use App\Http\Controllers\Admin\EnclosController;
use App\Http\Controllers\Admin\EnvironnementController;
use App\Http\Controllers\Admin\EspeceController;
use App\Http\Controllers\Admin\ModeLivraisonController;
use App\Http\Controllers\Admin\NourritureController;
use App\Http\Controllers\Admin\PaysController;
use App\Http\Controllers\Admin\PersonnelController;
use App\Http\Controllers\Admin\ProduitController;
use App\Http\Controllers\Admin\StatutCommandeController;
use App\Http\Controllers\Admin\TaxeController;
use App\Http\Controllers\Admin\TypeEnclosController;
use App\Http\Controllers\Admin\TypePersonnelController;
use App\Http\Controllers\FrontProduitController;
use App\Http\Controllers\PasserCommandeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

//Route::get('/', function () {
//    return view('welcome');
//});
//
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');


Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//admin
Route::get('/admin', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
Route::resource('/admin/caracteristiques', CaracteristiqueController::class);
Route::resource('/admin/categories-de-produit', CategorieProduitController::class);
Route::resource('/admin/climats', ClimatController::class);
Route::resource('/admin/enclos', EnclosController::class);
Route::resource('/admin/environnements', EnvironnementController::class);
Route::resource('/admin/especes', EspeceController::class);
Route::resource('/admin/modes-de-livraison', ModeLivraisonController::class);
Route::resource('/admin/nourritures', NourritureController::class);
Route::resource('/admin/pays', PaysController::class);
Route::resource('/admin/statuts-commandes', StatutCommandeController::class);
Route::resource('/admin/taxes', TaxeController::class);
Route::resource('/admin/types-enclos', TypeEnclosController::class);
Route::resource('/admin/types-personnel', TypePersonnelController::class);

Route::resource('/admin/adresses', AdresseController::class);
Route::resource('/admin/clients', ClientController::class);
Route::resource('/admin/commandes', CommandeController::class);
Route::resource('/admin/dinos', DinoController::class);
Route::resource('/admin/dino-enclos', DinoEnclosController::class)->only([
    'index', 'destroy'
]);
Route::resource('/admin/produits', ProduitController::class);
Route::resource('/admin/personnel', PersonnelController::class);

//test
Route::resource('/commander', PasserCommandeController::class);
Route::GET("/commander/panier/{id}", [PasserCommandeController::class, 'panierAdd'])->name('panier.add');
Route::GET("/commander/{id}", [PasserCommandeController::class, 'show'])->name('commander.show');
Route::POST("/commander/commande", [PasserCommandeController::class, 'commander'])->name('commander.commander');
Route::POST("/commander/validation", [PasserCommandeController::class, 'validation'])->name('commander.validation');
Route::get("/commander/panier", [PasserCommandeController::class, 'panier'])->name('panier');

require __DIR__.'/auth.php';

app/Models/Environnement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Environnement extends Model
{
    use HasFactory;

    protected $fillable = ['nom'];

    /**
     * @return BelongsToMany
     */
    public function enclos()
    {
        return $this->belongsToMany(
            Environnement::class);
    }
}

app/Http/Controllers/Admin/EnvironnementController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\SaveEnvironnementRequest;
use App\Models\Environnement;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class EnvironnementController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        $environnements = Environnement::select('id', 'nom', 'created_at', 'updated_at')->get();

        return view('admin.environnement.index', ['environnements' => $environnements]);
    }

    /**
     * @return Application|Factory|View
     */
    public function create(): View|Factory|Application
    {
        $environnement = new Environnement();

        return view('admin.environnement.create', ['environnement' => $environnement]);
    }

    /**
     * @param SaveEnvironnementRequest $request
     * @return RedirectResponse
     */
    public function store(SaveEnvironnementRequest $request): RedirectResponse
    {
        $environnement = Environnement::create($request->all());

        return redirect()->route('environnements.index')
            ->with('success', 'Vous venez d\'ajouter un nouvel environnement');
    }

    /**
     * @param $id
     * @return Application|Factory|View
     */
    public function show($id): View|Factory|Application
    {
        $environnement = Environnement::select('id', 'nom', 'created_at', 'updated_at')->findOrFAil($id);

        return view('admin.environnement.show', ['environnement' => $environnement]);
    }

    /**
     * @param $id
     * @return Application|Factory|View
     */
    public function edit($id): View|Factory|Application
    {
        $environnement = Environnement::find($id);

        return view('admin.environnement.edit', ['environnement' => $environnement]);
    }

    /**
     * @param SaveEnvironnementRequest $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(SaveEnvironnementRequest $request, int $id): RedirectResponse
    {
        Environnement::find($id)->update($request->all());

        return redirect()->route('environnements.index')
            ->with('success', 'L\'environnement à bien été modifié');
    }


    public function destroy($id): RedirectResponse
    {
        Environnement::find($id)->enclos()->detach();

        $environnement = Environnement::find($id)->delete();

        return redirect()->route('environnements.index')
            ->with('success', 'L\'environnement à bien été supprimé');
    }
}

resources/views/admin/environnement/create.blade.php
@extends('admin.base')

@section('title', 'Créer un environnement')

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('environnements.create')}}">Créer un environnement</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @includeif('partials.errors')
            <div class="card border-dark">
                <div class="card-header bg-dark">
                    <h5 class="card-title m-0">Ajouter</h5>
                </div>
                <div class="card-body">
                    {!! Form::open(['method' => 'POST', 'route' => 'environnements.store']) !!}
                    @csrf
                    @include('admin.environnement.form')
                    {{ Form::submit('Ajouter',['class'=>'btn btn-primary mt-3']) }}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/environnement/edit.blade.php
@extends('admin.base')

@section('title', 'Modifier l\'environnement')

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('environnements.edit', $environnement->id)}}">Modifier l'climat</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @includeif('partials.errors')
            <div class="card border-dark">
                <div class="card-header bg-dark">
                    <h5 class="card-title m-0">Modifier</h5>
                </div>
                <div class="card-body">
                    {!! Form::open(['method' => 'PUT', 'route' => ['environnements.update', $environnement->id]]) !!}
                    {{ method_field('PATCH') }}
                    @csrf
                    @include('admin.environnement.form')
                    {{ Form::submit('Modifier',['class'=>'btn btn-primary mt-3']) }}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/environnement/form.blade.php
<div class="form-group mt-3">
    {{ Form::label('Nom :') }}
    {{ Form::text('nom', $environnement->nom, ['class' => 'form-control' . ($errors->has('nom') ? ' is-invalid' : ''), 'placeholder' => 'Nom']) }}
    @error('nom')
    <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>

resources/views/admin/environnement/index.blade.php
@extends('admin.base')

@section('title', 'Environnements')

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('environnements.index')}}">Climats</a>
@endsection

@section('add')
    <a class="btn btn-primary" href="{{ route('environnements.create') }}">Ajouter</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif

            <div class="container-fluid border border-dark rounded pt-3 pb-2">
                <table class="admin_index table table-striped table-light table-hover nowrap" width="100%">

                    <thead class="table-dark">
                    <tr>
                        <th data-priority="1">id</th>
                        <th data-priority="2">Nom</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>@foreach ($environnements as $environnement)
                        <tr>
                            <td>{{ $environnement->id }}</td>
                            <td>{{ $environnement->nom }}</td>
                            <td>
                                <form action="{{ route('environnements.destroy',$environnement->id) }}" method="POST">
                                    <a class="btn btn-sm btn-primary "
                                       href="{{ route('environnements.show',$environnement->id) }}"><i
                                            class="fa fa-fw fa-eye"></i> Montrer</a>
                                    <a class="btn btn-sm btn-success"
                                       href="{{ route('environnements.edit',$environnement->id) }}"><i
                                            class="fa fa-fw fa-edit"></i> Modifer</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm"><i
                                            class="fa fa-fw fa-trash"></i> Supprimer
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/environnement/show.blade.php
@extends('admin.base')

@section('title', 'Environnement "' . $environnement->nom .'"' )

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('environnements.create')}}">Environnement
        <span>{{ $environnement->nom }}</span></a>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card border-dark">
                <div class="card-header d-flex align-items-center bg-dark">
                        <h5 class="card-title m-0">Ajouter</h5>
                    <div class="d-flex justify-content-end w-100">
                        <a class="btn btn-primary" href="{{ route('environnements.index') }}">Retour</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <b>Identifiant :</b>
                                    {{ $environnement->id }}
                                </div>
                                <div class="form-group">
                                    <b>Nom :</b>
                                    {{ $environnement->nom }}
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <div class="form-group">
                                    <b>Date d'ajout :</b>
                                    {{ $environnement->created_at }}
                                </div>
                                <div class="form-group">
                                    <b>Date de modification :</b>
                                    {{ $environnement->updated_at }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection