routes/web.php
<?php

use App\Http\Controllers\Admin\AdresseController;
use App\Http\Controllers\Admin\CaracteristiqueController;
use App\Http\Controllers\Admin\CategorieProduitController;
use App\Http\Controllers\Admin\ClientController;
use App\Http\Controllers\Admin\ClimatController;
use App\Http\Controllers\Admin\CommandeController;
use App\Http\Controllers\Admin\DinoController;
use App\Http\Controllers\Admin\DinoEnclosController;
use App\Http\Controllers\Admin\EnclosController;
use App\Http\Controllers\Admin\EnvironnementController;
use App\Http\Controllers\Admin\EspeceController;
use App\Http\Controllers\Admin\ModeLivraisonController;
use App\Http\Controllers\Admin\NourritureController;
use App\Http\Controllers\Admin\PaysController;
use App\Http\Controllers\Admin\PersonnelController;
use App\Http\Controllers\Admin\ProduitController;
use App\Http\Controllers\Admin\StatutCommandeController;
use App\Http\Controllers\Admin\TaxeController;
use App\Http\Controllers\Admin\TypeEnclosController;
use App\Http\Controllers\Admin\TypePersonnelController;
use App\Http\Controllers\FrontProduitController;
use App\Http\Controllers\PasserCommandeController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

//Route::get('/', function () {
//    return view('welcome');
//});
//
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');


Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//admin
Route::get('/admin', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('dashboard');
Route::resource('/admin/caracteristiques', CaracteristiqueController::class);
Route::resource('/admin/categories-de-produit', CategorieProduitController::class);
Route::resource('/admin/climats', ClimatController::class);
Route::resource('/admin/enclos', EnclosController::class);
Route::resource('/admin/environnements', EnvironnementController::class);
Route::resource('/admin/especes', EspeceController::class);
Route::resource('/admin/modes-de-livraison', ModeLivraisonController::class);
Route::resource('/admin/nourritures', NourritureController::class);
Route::resource('/admin/pays', PaysController::class);
Route::resource('/admin/statuts-commandes', StatutCommandeController::class);
Route::resource('/admin/taxes', TaxeController::class);
Route::resource('/admin/types-enclos', TypeEnclosController::class);
Route::resource('/admin/types-personnel', TypePersonnelController::class);

Route::resource('/admin/adresses', AdresseController::class);
Route::resource('/admin/clients', ClientController::class);
Route::resource('/admin/commandes', CommandeController::class);
Route::resource('/admin/dinos', DinoController::class);
Route::resource('/admin/dino-enclos', DinoEnclosController::class)->only([
    'index', 'destroy'
]);
Route::resource('/admin/produits', ProduitController::class);
Route::resource('/admin/personnel', PersonnelController::class);

//test
Route::resource('/commander', PasserCommandeController::class);
Route::GET("/commander/panier/{id}", [PasserCommandeController::class, 'panierAdd'])->name('panier.add');
Route::GET("/commander/{id}", [PasserCommandeController::class, 'show'])->name('commander.show');
Route::POST("/commander/commande", [PasserCommandeController::class, 'commander'])->name('commander.commander');
Route::POST("/commander/validation", [PasserCommandeController::class, 'validation'])->name('commander.validation');
Route::get("/commander/panier", [PasserCommandeController::class, 'panier'])->name('panier');

require __DIR__.'/auth.php';

app/Models/Commande.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Commande extends Model
{
    use HasFactory;

    protected $fillable = ['prix_ttc', 'mode_livraison_id', 'statut_commande_id', 'client_id'];

    /**
     * @return BelongsTo
     */
    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    /**
     * @return BelongsTo
     */
    public function modeLivraison()
    {
        return $this->belongsTo(ModeLivraison::class);
    }

    /**
     * @return BelongsTo
     */
    public function statutCommande()
    {
        return $this->belongsTo(StatutCommande::class);
    }

    /**
     * @return BelongsToMany
     */
    public function produits()
    {
        return $this->belongsToMany(Produit::class, 'ligne_commande')
            ->withPivot('quantite', 'prix_ht', 'taux')
            ->withTimestamps();
    }

    /**
     * @return string
     */
    public function getPrixTtc()
    {
      return $this->prix_ttc . '€';
    }
}

app/Http/Controllers/Admin/CommandeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Client;
use App\Models\ModeLivraison;
use App\Models\StatutCommande;
use Illuminate\Http\Request;
use App\Models\Commande;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class CommandeController extends Controller
{
    /**
     * @return Application|Factory|View
     */
    public function index()
    {
        $commandes = Commande::with('modeLivraison:id,nom', 'statutCommande:id,nom', 'client:id,nom,prenom')
            ->select('id', 'prix_ttc', 'mode_livraison_id', 'statut_commande_id', 'client_id')
            ->orderByDesc('created_at')
            ->get();

        return view('admin.commande.index', ['commandes' => $commandes]);
    }

    /**
     * @param $id
     * @return Application|Factory|View
     */
    public function show($id)
    {
        $commande = Commande::with('modeLivraison:id,nom', 'statutCommande:id,nom', 'client:id,nom,prenom')
            ->select('id', 'prix_ttc', 'created_at', 'updated_at', 'mode_livraison_id', 'statut_commande_id', 'client_id')
            ->orderByDesc('created_at')
            ->findOrFail($id);

        return view('admin.commande.show', ['commande' => $commande]);
    }

    /**
     * @param $id
     * @return Application|Factory|View
     */
    public function edit($id)
    {
        $commande = Commande::find($id);
        $mode = ModeLivraison::pluck('nom', 'id');
        $statut = StatutCommande::pluck('nom', 'id');

        return view('admin.commande.edit', [
            'commande' => $commande,
            'mode' => $mode,
            'statut' => $statut,
        ]);
    }

    /**
     * @param Request $request
     * @param int $id
     * @return RedirectResponse
     */
    public function update(Request $request, int $id)
    {
        Commande::find($id)->update($request->all());

        return redirect()->route('commandes.index')
            ->with('success', 'L\commande à bien été modifiée');
    }

    /**
     * @param $id
     * @return RedirectResponse
     */
    public function destroy($id)
    {
        $commande = Commande::find($id)->delete();

        return redirect()->route('commandes.index')
            ->with('success', 'L\commande à bien été supprimée');
    }
}

resources/views/admin/commande/edit.blade.php
@extends('admin.base')

@section('title', 'Modifier la commande')

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('commandes.edit', $commande->id)}}">Modifier la commande </a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @includeif('partials.errors')
            <div class="card border-dark">
                <div class="card-header bg-dark">
                    <h5 class="card-title m-0">Modifier</h5>
                </div>
                <div class="card-body">
                    {!! Form::open(['method' => 'PUT', 'route' => ['commandes.update', $commande->id]]) !!}
                    {{ method_field('PATCH') }}
                    @csrf
                    @include('admin.commande.form')
                    {{ Form::submit('Modifier',['class'=>'btn btn-primary mt-3']) }}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/commande/form.blade.php
<div class="form-group mt-3">
    {{ Form::label('Prix TTC :') }}
    {{ Form::text('prix_ttc', $commande->prix_ttc, ['class' => 'form-control' . ($errors->has('prix_ttc') ? ' is-invalid' : ''), 'placeholder' => 'Prix TTC']) }}
    @error('prix_ttc')
    <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
    @enderror
</div>

<div class="form-group mt-3">
    {{ Form::label('Mode de livraison :') }}
        {{ Form::select('mode_livraison_id', $mode, $commande->mode_livraison_id,['class' => 'form-select']) }}
    @error('mode_livraison_id')
    <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
    @enderror
</div>

<div class="form-group mt-3">
    {{ Form::label('Statut de la commande :') }}
        {{ Form::select('statut_commande_id', $statut, $commande->statut_commande_id,['class' => 'form-select']) }}
    @error('statut_commande_id')
    <span class="invalid-feedback" role="alert">
                <strong>{{ $message }}</strong>
            </span>
    @enderror
</div>

resources/views/admin/commande/index.blade.php
@extends('admin.base')

@section('title', 'Commandes')

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('commandes.index')}}">Commandes</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-sm-12">

            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
            @endif

            <div class="container-fluid border border-dark rounded pt-3 pb-2">
                <table class="admin_index table table-striped table-light table-hover nowrap" width="100%">

                    <thead class="table-dark">
                    <tr>
                        <th data-priority="1">id</th>
                        <th data-priority="2">Prix ttc</th>
                        <th>Mode de livraison</th>
                        <th>Statut de la commande</th>
                        <th>Client</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>@foreach ($commandes as $commande)
                        <tr>
                            <td>{{ $commande->id }}</td>
                            <td>{{ $commande->getPrixTtc() }}</td>
                            <td>{{ $commande->modeLivraison->nom }}</td>
                            <td>{{ $commande->statutCommande->nom }}</td>
                            <td>{{ $commande->client->getFullname() }}</td>
                            <td>
                                <form action="{{ route('commandes.destroy',$commande->id) }}" method="POST">
                                    <a class="btn btn-sm btn-primary "
                                       href="{{ route('commandes.show',$commande->id) }}"><i
                                            class="fa fa-fw fa-eye"></i> Montrer</a>
                                    <a class="btn btn-sm btn-success"
                                       href="{{ route('commandes.edit',$commande->id) }}"><i
                                            class="fa fa-fw fa-edit"></i> Modifer</a>
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm"><i
                                            class="fa fa-fw fa-trash"></i> Supprimer
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/commande/show.blade.php
@extends('admin.base')

@section('title', 'Commande "' . $commande->nom .'"' )

@section('content-header')
    <a class="text-decoration-none text-black" href="{{ route('commandes.create')}}">Commande
        <span>{{ $commande->nom }}</span></a>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">

            <div class="card border-dark">
                <div class="card-header d-flex align-items-center bg-dark">
                        <h5 class="card-title m-0">Ajouter</h5>
                    <div class="d-flex justify-content-end w-100">
                        <a class="btn btn-primary" href="{{ route('commandes.index') }}">Retour</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-12 col-lg-4">
                                <div class="form-group">
                                    <b>Identifiant :</b>
                                    {{ $commande->id }}
                                </div>
                                <div class="form-group">
                                    <b>Client :</b>
                                    {{ $commande->client->getFullname() }}
                                </div>
                                <div class="form-group">
                                    <b>Total ttc :</b>
                                    {{ $commande->getPrixTtc() }}
                                </div>
                            </div>
                            <div class="col-12 col-lg-4">
                                <div class="form-group">
                                    <b>statut de la commande :</b>
                                    {{ $commande->statutCommande->nom }}
                                </div>
                                <div class="form-group">
                                    <b>Mode de livraison :</b>
                                    {{$commande->modeLivraison->nom }}
                                </div>
                            </div>
                            <div class="col-12 col-lg-4">
                                <div class="form-group">
                                    <b>Date d'ajout :</b>
                                    {{ $commande->created_at }}
                                </div>
                                <div class="form-group">
                                    <b>Date de modification :</b>
                                    {{ $commande->updated_at }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection